name: file-server

services:
  app:
    image: file-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: file-server
    restart: unless-stopped
    ports:
      - "4443:4443"
    volumes:
      - ./files:/data:Z
